import sys
content = open(sys.argv[1]).read()
content = content.replace("._main", ".main").replace("._extern", ".extern")
content = content.replace(".global _", ".global ").replace("call _", "call ")
content = content.replace("._printf", ".printf").replace("._malloc", ".malloc")
content = content.replace("._free", ".free").replace("._realloc", ".realloc")
content = content.replace("._fopen", ".fopen").replace("._fclose", ".fclose")
content = content.replace("._fread", ".fread").replace("._fwrite", ".fwrite")
content = content.replace("._fputs", ".fputs").replace("._fputc", ".fputc")
content = content.replace("._fseek", ".fseek").replace("._ftell", ".ftell")
content = content.replace("._fflush", ".fflush").replace("._exit", ".exit")
content = content.replace("._system", ".system").replace("._strlen", ".strlen")
content = content.replace("._strcmp", ".strcmp").content = content.replace("._strcpy", ".strcpy")
content = content.replace("._strcat", ".strcat").replace("._strstr", ".strstr")
content = content.replace("._memset", ".memset").replace("._sprintf", ".sprintf")
content = content.replace("._dict_new", ".dict_new").replace("._dict_get", ".dict_get")
content = content.replace("._dict_set", ".dict_set").replace("._dict_has", ".dict_has")
content = content.replace("._dict_remove", ".dict_remove").replace("._dict_keys", ".dict_keys")
content = content.replace("._dict_values", ".dict_values").replace("._dict_items", ".dict_items")
content = content.replace("._concat_strings", ".concat_strings")
content = content.replace("._slice_string", ".slice_string")
content = content.replace("._out_of_bounds", ".out_of_bounds")
content = content.replace("._sys_read", ".sys_read")
content = content.replace("._main", "main").replace(":_main", "main:")
# Fix remaining function calls
import re
content = re.sub(r'call _([a-zA-Z_][a-zA-Z0-9_]*)', r'call \1', content)
content = re.sub(r'\.global _([a-zA-Z_][a-zA-Z0-9_]*)', r'.global \1', content)
content = re.sub(r'^_([a-zA-Z_][a-zA-Z0-9_]*):', r'\1:', content, flags=re.MULTILINE)
open(sys.argv[1], 'w').write(content)
